services:
  gateway:

    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - msa-net


networks:
  msa-net:
    external: true
