server:
  port: 8080

jwt:
  secret: ${JWT_SECRET_KEY}

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://auth_service_app:8081  # 실제 auth-service 주소
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
      default-filters:
        - name: GlobalCorsConfig

---

# 선택적으로 로깅 등 추가
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
