server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth_service_app:8081/
              predicates:
               - Path=/auth/**
              filters:
               - StripPrefix=0
#               - AddRequestHeader=first-request, first-request-header2
#               - AddResponseHeader=first-response, first-response-header2

jwt:
  secret: ${JWT_SECRET_KEY}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
