server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081  # 실제 auth-service 주소
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1  # /auth/login → /login 으로 전달

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - name: JwtFilter

      default-filters:
        - name: GlobalCorsConfig

---

# 선택적으로 로깅 등 추가
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
